name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Heimerhui69
          POSTGRES_DB: budzetownik
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d budzetownik"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DATABASE_URL: postgresql://postgres:Heimerhui69@localhost:5432/budzetownik?schema=public

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Apply Prisma schema to test DB
        run: npx prisma db push --skip-generate

      - name: Check commit name
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run prettier
        if: always()
        run: npm run format:check

      - name: Run Lint
        if: always()
        run: npm run lint

      - name: Check types
        if: always()
        run: npm run typecheck

      - name: Unit tests
        if: always()
        run: npm test -- --runInBand

      - name: E2E tests
        if: always()
        run: npm run test:e2e -- --runInBand

      - name: Build
        if: always()
        run: npm run build
